modLoader="javafml"
loaderVersion="[45,)"
license="All rights reserved"
issueTrackerURL="https://github.com/ricksouth/serilum-mc-mods/labels/Mod:%20Welcome%20Message"
logoFile="icon.png"

[[mods]]
modId="welcomemessage"
version="2.1"
displayName="Welcome Message"
displayURL="https://curseforge.com/minecraft/mc-mods/welcome-message"
authors="Rick South"
description='''An easy to configure welcome message mod for players after login with URL support.
If you would like to contribute too, check out https://ricksouth.com/donate. Appreciate it! <3   
'''
credits='''Thank you very much to my Membership sponsors for supporting the development of this mod:  

Adam E, Alister, aternosorg, Cherriesaurus, Greg Johnson, Kreezxil, Michael W. S., Mir3JonCZ, nbtc971, Rebecca Hb., Robert Gilbert, Shana Gitnick, Sija, silver Bowsman, Tyler Behl   

If you would like to contribute too, check out https://ricksouth.com/donate. Appreciate it! <3   
'''

[[dependencies.welcomemessage]]
    modId="collective"
    mandatory=true
    versionRange="[6.53,)"
    ordering="NONE"
    side="BOTH"